package com.altrex.mobile.data.multiai

import com.altrex.mobile.data.model.ChatMessage
import com.altrex.mobile.data.provider.ProviderService
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.util.UUID

/**
 * Phases of the multi-AI director lifecycle.
 */
enum class DirectorPhase(val value: String) {
    PLANNING("PLANNING"),
    RUNNING("RUNNING"),
    VERIFYING("VERIFYING"),
    INTEGRATING("INTEGRATING"),
    COMPLETED("COMPLETED"),
    FAILED("FAILED");

    companion object {
        fun fromValue(value: String): DirectorPhase? =
            values().find { it.value == value }
    }
}

/**
 * A single task within a director plan.
 */
@Serializable
data class DirectorTask(
    val id: String,
    val name: String,
    val description: String,
    val specialistType: String = "general",
    val dependencies: List<String> = emptyList(),
    val scope: List<String> = emptyList(),
    val model: String? = null,
    val status: String = "PENDING",
    val result: String? = null
)

/**
 * A plan generated by the director during the PLANNING phase.
 */
@Serializable
data class DirectorPlan(
    val id: String,
    val objective: String,
    val tasks: List<DirectorTask>,
    val createdAt: Long = System.currentTimeMillis()
) {
    val taskById: Map<String, DirectorTask>
        get() = tasks.associateBy { it.id }
}

/**
 * Final result of a director run.
 */
@Serializable
data class DirectorResult(
    val runId: String,
    val status: DirectorStatus,
    val integratedOutput: String?,
    val taskResults: Map<String, String>,
    val errors: List<String> = emptyList(),
    val roundsCompleted: Int = 0
)

enum class DirectorStatus { SUCCESS, PARTIAL, FAILED }

/**
 * Events emitted during director execution.
 */
sealed class DirectorEvent {
    data class PhaseChanged(val phase: DirectorPhase) : DirectorEvent()
    data class PlanGenerated(val plan: DirectorPlan) : DirectorEvent()
    data class PlanValidationFailed(val errors: List<String>) : DirectorEvent()
    data class TaskStarted(val taskId: String, val taskName: String) : DirectorEvent()
    data class TaskCompleted(val taskId: String, val result: String) : DirectorEvent()
    data class TaskFailed(val taskId: String, val error: String) : DirectorEvent()
    data class TaskSkipped(val taskId: String, val reason: String) : DirectorEvent()
    data class VerificationPassed(val taskId: String) : DirectorEvent()
    data class VerificationFailed(val taskId: String, val issues: List<String>) : DirectorEvent()
    data class IntegrationCompleted(val output: String) : DirectorEvent()
    data class DirectorError(val message: String) : DirectorEvent()
    data class StatePersisted(val runId: String, val phase: DirectorPhase) : DirectorEvent()
    object Completed : DirectorEvent()
}

/**
 * Callback for receiving director events.
 */
fun interface DirectorEventCallback {
    suspend fun onEvent(event: DirectorEvent)
}

/**
 * Configuration for a director run.
 *
 * @param connectionId the provider connection to use
 * @param planningModel model for the planning phase
 * @param executionModel default model for task execution
 * @param integrationModel model for the integration phase
 * @param temperature sampling temperature
 * @param maxTokens maximum tokens per completion
 * @param projectRoot virtual project root path
 * @param projectId identifier for the project (for state persistence)
 */
data class DirectorConfig(
    val connectionId: String,
    val planningModel: String = "gpt-4o",
    val executionModel: String = "gpt-4o-mini",
    val integrationModel: String = "gpt-4o",
    val temperature: Double = 0.2,
    val maxTokens: Int = 4_096,
    val projectRoot: String = "/",
    val projectId: String = "default"
)

/**
 * Multi-AI Director that orchestrates a 4-phase lifecycle:
 *
 * 1. **PLANNING** — asks the LLM to decompose the objective into a set of
 *    specialist tasks with dependencies and scopes. The generated plan is
 *    validated by [PlanValidator].
 * 2. **RUNNING** — executes tasks in dependency order (topological sort).
 *    Each task is sent to the LLM with its description and the results of
 *    its dependencies. Progress is persisted via [StateStore] for crash
 *    recovery.
 * 3. **VERIFYING** — checks that each task produced a non-empty result.
 * 4. **INTEGRATING** — sends all task results to the LLM to produce a
 *    final integrated output.
 *
 * This is the Android adaptation of the desktop app's director — it uses
 * simplified workspace staging (state tracking only, no local file copying)
 * and relies on [ProviderService] for all LLM calls.
 */
class Director(
    private val providerService: ProviderService,
    private val stateStore: StateStore,
    private val eventCallback: DirectorEventCallback = DirectorEventCallback { }
) {
    private val json = Json {
        ignoreUnknownKeys = true
        encodeDefaults = true
    }

    /**
     * Executes the full director lifecycle for the given [objective].
     */
    suspend fun execute(objective: String, config: DirectorConfig): DirectorResult {
        val runId = UUID.randomUUID().toString()
        val errors = mutableListOf<String>()

        try {
            // ── PLANNING ──────────────────────────────────────────────────
            emitPhase(DirectorPhase.PLANNING)

            val plan = planningPhase(objective, config, runId)
                ?: return failResult(runId, errors, "Planning failed")

            // Persist initial state
            stateStore.createRun(
                runId = runId,
                projectId = config.projectId,
                objective = objective,
                tasks = plan.tasks.map { it.toTaskState() }
            )
            eventCallback.onEvent(DirectorEvent.StatePersisted(runId, DirectorPhase.PLANNING))

            // ── RUNNING ───────────────────────────────────────────────────
            emitPhase(DirectorPhase.RUNNING)
            stateStore.updatePhase(runId, DirectorPhase.RUNNING)

            val taskResults = runningPhase(plan, config, runId, errors)

            // ── VERIFYING ─────────────────────────────────────────────────
            emitPhase(DirectorPhase.VERIFYING)
            stateStore.updatePhase(runId, DirectorPhase.VERIFYING)

            val verificationIssues = verifyingPhase(plan, taskResults)
            for ((taskId, issues) in verificationIssues) {
                if (issues.isEmpty()) {
                    eventCallback.onEvent(DirectorEvent.VerificationPassed(taskId))
                } else {
                    eventCallback.onEvent(DirectorEvent.VerificationFailed(taskId, issues))
                    errors.addAll(issues)
                }
            }

            // ── INTEGRATING ───────────────────────────────────────────────
            emitPhase(DirectorPhase.INTEGRATING)
            stateStore.updatePhase(runId, DirectorPhase.INTEGRATING)

            val integratedOutput = integratingPhase(plan, taskResults, config)

            // Complete
            stateStore.completeRun(runId, integratedOutput)
            emitPhase(DirectorPhase.COMPLETED)
            eventCallback.onEvent(DirectorEvent.IntegrationCompleted(integratedOutput))
            eventCallback.onEvent(DirectorEvent.Completed)

            val status = when {
                errors.isEmpty() -> DirectorStatus.SUCCESS
                taskResults.size == plan.tasks.size -> DirectorStatus.PARTIAL
                else -> DirectorStatus.PARTIAL
            }

            return DirectorResult(
                runId = runId,
                status = status,
                integratedOutput = integratedOutput,
                taskResults = taskResults,
                errors = errors
            )

        } catch (e: Exception) {
            val errorMsg = e.message ?: "Unknown director error"
            errors.add(errorMsg)
            eventCallback.onEvent(DirectorEvent.DirectorError(errorMsg))
            stateStore.failRun(runId, errorMsg)
            emitPhase(DirectorPhase.FAILED)
            return DirectorResult(
                runId = runId,
                status = DirectorStatus.FAILED,
                integratedOutput = null,
                taskResults = emptyMap(),
                errors = errors
            )
        }
    }

    // ── Phase implementations ───────────────────────────────────────────────

    /**
     * PLANNING phase: asks the LLM to decompose the objective into tasks.
     */
    private suspend fun planningPhase(
        objective: String,
        config: DirectorConfig,
        runId: String
    ): DirectorPlan? {
        val systemPrompt = buildString {
            appendLine("You are the ALTREX CODE Director, a multi-AI orchestrator.")
            appendLine("Your job is to break down the given objective into a set of specialist tasks.")
            appendLine()
            appendLine("Respond with a JSON object in exactly this format:")
            appendLine("""{"tasks":[{"id":"task-1","name":"...","description":"...","specialistType":"...","dependencies":["task-0"],"scope":["src/"],"model":"gpt-4o-mini"}]}""")
            appendLine()
            appendLine("Rules:")
            appendLine("- Each task must have a unique id (e.g. \"task-1\", \"task-2\").")
            appendLine("- Dependencies must reference other task ids.")
            appendLine("- Scope lists the file paths/directories the task may touch.")
            appendLine("- Specialist types: general, coder, reviewer, tester, documenter.")
            appendLine("- Keep the number of tasks reasonable (1-10).")
        }

        val messages = listOf(
            ChatMessage(role = "system", content = systemPrompt),
            ChatMessage(role = "user", content = "Objective: $objective")
        )

        val response = callLlm(
            connectionId = config.connectionId,
            messages = messages,
            model = config.planningModel,
            config = config
        ) ?: return null

        val planJson = parsePlanJson(response)
            ?: run {
                eventCallback.onEvent(
                    DirectorEvent.DirectorError("Failed to parse plan JSON from LLM response")
                )
                return null
            }

        // Validate the plan
        val validation = PlanValidator.validatePlan(planJson)
        if (validation is ValidationResult.Invalid) {
            eventCallback.onEvent(DirectorEvent.PlanValidationFailed(validation.errors))
            return null
        }

        val plan = DirectorPlan(
            id = runId,
            objective = objective,
            tasks = parseTasks(planJson)
        )

        eventCallback.onEvent(DirectorEvent.PlanGenerated(plan))
        return plan
    }

    /**
     * RUNNING phase: executes tasks in dependency order.
     */
    private suspend fun runningPhase(
        plan: DirectorPlan,
        config: DirectorConfig,
        runId: String,
        errors: MutableList<String>
    ): Map<String, String> {
        val results = mutableMapOf<String, String>()
        val sortedTasks = topologicalSort(plan.tasks)

        for (task in sortedTasks) {
            // Skip already-completed tasks (crash recovery)
            if (task.status == "COMPLETED" && task.result != null) {
                results[task.id] = task.result
                eventCallback.onEvent(
                    DirectorEvent.TaskSkipped(task.id, "Already completed")
                )
                continue
            }

            eventCallback.onEvent(
                DirectorEvent.TaskStarted(task.id, task.name)
            )

            // Build context from dependency results
            val depContext = buildDependencyContext(task, plan, results)

            val taskPrompt = buildString {
                appendLine("You are a specialist agent working on a subtask.")
                appendLine("Specialist type: ${task.specialistType}")
                appendLine()
                appendLine("## Task")
                appendLine(task.description)
                appendLine()
                if (depContext.isNotEmpty()) {
                    appendLine("## Context from Dependencies")
                    appendLine(depContext)
                    appendLine()
                }
                if (task.scope.isNotEmpty()) {
                    appendLine("## Allowed Scope")
                    task.scope.forEach { appendLine("- $it") }
                    appendLine()
                }
                appendLine("## Instructions")
                appendLine("Complete this task and provide a clear, concise result.")
            }

            val messages = listOf(
                ChatMessage(role = "system", content = "You are a specialist coding agent."),
                ChatMessage(role = "user", content = taskPrompt)
            )

            val model = task.model ?: config.executionModel
            val result = callLlm(
                connectionId = config.connectionId,
                messages = messages,
                model = model,
                config = config
            )

            if (result != null) {
                results[task.id] = result
                stateStore.updateTaskResult(runId, task.id, result, "COMPLETED")
                eventCallback.onEvent(
                    DirectorEvent.TaskCompleted(task.id, result)
                )
            } else {
                errors.add("Task '${task.name}' (${task.id}) failed")
                stateStore.updateTaskResult(runId, task.id, "", "FAILED")
                eventCallback.onEvent(
                    DirectorEvent.TaskFailed(task.id, "LLM call returned null")
                )
                // Continue with remaining tasks — some may not depend on this one
            }
        }

        return results
    }

    /**
     * VERIFYING phase: checks that each task produced a non-empty result.
     */
    private suspend fun verifyingPhase(
        plan: DirectorPlan,
        results: Map<String, String>
    ): Map<String, List<String>> {
        val issues = mutableMapOf<String, List<String>>()

        for (task in plan.tasks) {
            val taskIssues = mutableListOf<String>()
            val result = results[task.id]

            if (result == null) {
                taskIssues.add("Task has no result")
            } else if (result.isBlank()) {
                taskIssues.add("Task result is empty")
            }

            // Validate scope if the task declares one
            if (task.scope.isNotEmpty() && result != null) {
                val scopeValidation = ScopeValidator.validateScope(
                    targetFiles = extractFileReferences(result),
                    allowedScope = task.scope
                )
                if (scopeValidation is ValidationResult.Invalid) {
                    taskIssues.addAll(scopeValidation.errors)
                }
            }

            issues[task.id] = taskIssues
        }

        return issues
    }

    /**
     * INTEGRATING phase: asks the LLM to combine all task results.
     */
    private suspend fun integratingPhase(
        plan: DirectorPlan,
        results: Map<String, String>,
        config: DirectorConfig
    ): String {
        val taskSummaries = buildString {
            for (task in plan.tasks) {
                val result = results[task.id]
                appendLine("### ${task.name} (${task.id})")
                appendLine("Specialist: ${task.specialistType}")
                appendLine("Result:")
                appendLine(result ?: "(no result — task failed or was skipped)")
                appendLine()
            }
        }

        val systemPrompt = buildString {
            appendLine("You are the ALTREX CODE Director in the INTEGRATING phase.")
            appendLine("Below are the results of specialist tasks that were executed to achieve an objective.")
            appendLine("Your job is to integrate them into a single, coherent final output.")
            appendLine("Resolve conflicts, fill gaps, and produce a clean, complete result.")
        }

        val userPrompt = buildString {
            appendLine("## Objective")
            appendLine(plan.objective)
            appendLine()
            appendLine("## Task Results")
            appendLine(taskSummaries)
            appendLine()
            appendLine("## Instructions")
            appendLine("Integrate all results into a final output that fulfills the objective.")
        }

        val messages = listOf(
            ChatMessage(role = "system", content = systemPrompt),
            ChatMessage(role = "user", content = userPrompt)
        )

        return callLlm(
            connectionId = config.connectionId,
            messages = messages,
            model = config.integrationModel,
            config = config
        ) ?: "Integration failed: LLM returned no content"
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    private suspend fun emitPhase(phase: DirectorPhase) {
        eventCallback.onEvent(DirectorEvent.PhaseChanged(phase))
    }

    /**
     * Calls the LLM via ProviderService.complete and returns the content,
     * or null on failure.
     */
    private suspend fun callLlm(
        connectionId: String,
        messages: List<ChatMessage>,
        model: String,
        config: DirectorConfig
    ): String? {
        return try {
            val result = providerService.complete(
                connectionId = connectionId,
                messages = messages,
                model = model,
                temperature = config.temperature,
                maxTokens = config.maxTokens
            )
            if (result.isSuccess) result.getOrThrow() else null
        } catch (e: Exception) {
            eventCallback.onEvent(DirectorEvent.DirectorError("LLM call failed: ${e.message}"))
            null
        }
    }

    /**
     * Parses the LLM's JSON response into a JsonObject.
     * Handles cases where the JSON is wrapped in markdown code blocks.
     */
    private fun parsePlanJson(response: String): JsonObject? {
        val cleaned = response
            .replace(Regex("^```(?:json)?\\s*", RegexOption.MULTILINE), "")
            .replace(Regex("\\s*```$", RegexOption.MULTILINE), "")
            .trim()

        return try {
            json.parseToJsonElement(cleaned).jsonObject
        } catch (e: Exception) {
            null
        }
    }

    /**
     * Extracts DirectorTask list from a parsed plan JSON object.
     */
    private fun parseTasks(planJson: JsonObject): List<DirectorTask> {
        val tasksArray = planJson["tasks"] as? JsonArray ?: return emptyList()
        return tasksArray.mapNotNull { element ->
            val obj = element as? JsonObject ?: return@mapNotNull null
            DirectorTask(
                id = obj["id"]?.jsonPrimitive?.contentOrNull ?: return@mapNotNull null,
                name = obj["name"]?.jsonPrimitive?.contentOrNull ?: "Unnamed",
                description = obj["description"]?.jsonPrimitive?.contentOrNull ?: "",
                specialistType = obj["specialistType"]?.jsonPrimitive?.contentOrNull ?: "general",
                dependencies = (obj["dependencies"] as? JsonArray)
                    ?.mapNotNull { it.jsonPrimitive.contentOrNull } ?: emptyList(),
                scope = (obj["scope"] as? JsonArray)
                    ?.mapNotNull { it.jsonPrimitive.contentOrNull } ?: emptyList(),
                model = obj["model"]?.jsonPrimitive?.contentOrNull
            )
        }
    }

    /**
     * Topological sort of tasks based on their dependencies.
     * Tasks with no dependencies come first.
     */
    private fun topologicalSort(tasks: List<DirectorTask>): List<DirectorTask> {
        val taskMap = tasks.associateBy { it.id }
        val visited = mutableSetOf<String>()
        val result = mutableListOf<DirectorTask>()

        fun visit(taskId: String) {
            if (taskId in visited) return
            val task = taskMap[taskId] ?: return
            visited.add(taskId)
            for (dep in task.dependencies) {
                visit(dep)
            }
            result.add(task)
        }

        for (task in tasks) {
            visit(task.id)
        }

        return result
    }

    /**
     * Builds context string from a task's completed dependencies.
     */
    private fun buildDependencyContext(
        task: DirectorTask,
        plan: DirectorPlan,
        results: Map<String, String>
    ): String {
        if (task.dependencies.isEmpty()) return ""

        return buildString {
            for (depId in task.dependencies) {
                val depTask = plan.taskById[depId] ?: continue
                val depResult = results[depId] ?: "(not yet completed)"
                appendLine("**${depTask.name}**:")
                appendLine(depResult)
                appendLine()
            }
        }
    }

    /**
     * Extracts file path references from a text result for scope validation.
     */
    private fun extractFileReferences(text: String): List<String> {
        val pathPattern = Regex("""[\w/]+\.\w+""")
        return pathPattern.findAll(text).map { it.value }.toList()
    }

    private fun DirectorTask.toTaskState(): TaskState = TaskState(
        id = id,
        name = name,
        description = description,
        specialistType = specialistType,
        dependencies = dependencies,
        scope = scope,
        model = model,
        status = status,
        result = result
    )

    private fun failResult(
        runId: String,
        errors: MutableList<String>,
        message: String
    ): DirectorResult {
        errors.add(message)
        eventCallback.onEvent(DirectorEvent.DirectorError(message))
        stateStore.failRun(runId, message)
        emitPhase(DirectorPhase.FAILED)
        return DirectorResult(
            runId = runId,
            status = DirectorStatus.FAILED,
            integratedOutput = null,
            taskResults = emptyMap(),
            errors = errors.toList()
        )
    }
}
